[package]
name = "tcg-irdump"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tcg-irdump"
path = "src/main.rs"

[dependencies]
tcg-core = { path = "../../core" }
tcg-disas = { path = "../../disas" }
tcg-frontend = { path = "../../frontend" }
